
services:
  postgres:
    image: postgres:latest
    container_name: test_postgres
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge