-- -- Insert users
--
-- INSERT INTO users (email, firstname, lastname, telephone, role, password)
-- VALUES ('user1@xyz.com', 'User1', 'Lastname1', '09123456789', 'USER', 'encryptedpassword1');
--
-- INSERT INTO users (email, firstname, lastname, telephone, role, password)
-- VALUES ('user2@xyz.com', 'User2', 'Lastname2', '09876543210', 'OWNER', 'encryptedpassword2');
--
-- -- Insert cashcards associated with the above users
-- INSERT INTO cash_card (amount, owner, user_id)
-- VALUES (100.00, 'User1', (SELECT id FROM users WHERE email = 'user1@xyz.com'));
--
-- INSERT INTO cash_card (amount, owner, user_id)
-- VALUES (200.00, 'User2', (SELECT id FROM users WHERE email = 'user2@xyz.com'));
